In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_excel('Sales_mini_project.xlsx')

In [3]:
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001 2023-01-13    Rohit  South   Mobile  23289  19118
1      1002 2023-10-07     Aman   West   Laptop   8905   5593
2      1003 2023-11-05    Rahul  South  Monitor  59987  39959
3      1004 2024-02-19    Rahul  South  Printer  49597  33892
4      1005 2024-01-26   Anjali  North   Laptop  54797  34468

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    520 non-null    int64
 1   Order_Date  502 non-null    datetime64[ns]
 2   Customer    520 non-null    object
 3   Region      520 non-null    object
 4   Product     520 non-null    object
 5   Sales       520 non-null    int64
 6   Cost        520 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 28.6+ KB

In [5]:
df.describe()

          Order_ID                     Order_Date         Sales          Cost
count   520.000000                            502    520.000000    520.000000
mean   1250.867308  2023-08-18 09:36:34.422310656  41129.607692  30675.001923
min    1001.000000            2023-01-04 00:00:00   5205.000000   3272.000000
25%    1124.750000            2023-05-03 00:00:00  22015.750000  16388.000000
50%    1251.500000            2023-08-15 00:00:00  41044.000000  30349.000000
75%    1377.250000            2023-12-12 00:00:00  59245.000000  43363.500000
max    1500.000000            2024-03-26 00:00:00  79928.000000  71417.000000
std     145.030140                            NaN  21605.117122  16598.086873

In [6]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [7]:
# remove duplicate

df= df.drop_duplicates()

In [8]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [9]:
# Fix date coulmn

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

C:\Users\user\AppData\Local\Temp\ipykernel_22328\4279446220.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [10]:
df= df.dropna(subset=['Order_Date'])

In [11]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [12]:
df['Profit'] = df['Sales']-df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

C:\Users\user\AppData\Local\Temp\ipykernel_22328\3679951826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = df['Sales']-df['Cost']
C:\Users\user\AppData\Local\Temp\ipykernel_22328\3679951826.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Order_Date'].dt.year
C:\Users\user\AppData\Local\Temp\ipykernel_22328\3679951826.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month

In [13]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [14]:
df.to_csv('sales_cleaned.csv', index=False)

 # Data python +Excel+ SQL

In [15]:
import pandas as pd
from sqlalchemy import create_engine

In [16]:
df= pd.read_csv('sales_cleaned.csv')

In [17]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [24]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="Anisa@2025",
    host="localhost",
    port=3306,
    database="sales_db"
)

engine = create_engine(connection_url)

with engine.connect() as connection:
    print("MySQL connected successfully!")

MySQL connected successfully!

In [25]:
df.to_sql(name='sales_data',con=engine,if_exists='replace',index=False)

482

In [2]:
df = pd.read_csv("sales_raw_new_2026.csv")

In [3]:
df

     Order_ID  Order_Date Customer Region  Product  Sales   Cost
0        2001  2026-01-21     Neha   West   Laptop  16494  13135
1        2002  2026-01-07   Anjali  North  Monitor  35140  19722
2        2003  2026-01-28    Vikas  North   Mobile  18889  13511
3        2004  2026-01-04    Kiran  North   Mobile  89657  66187
4        2005  2026-03-02    Rahul   West   Laptop  35977  20290
..        ...         ...      ...    ...      ...    ...    ...
195      2196  2026-01-26    Kiran   East  Printer  28305  16671
196      2197  2026-01-04   Suresh  South  Printer  18669  13476
197      2198  2026-03-01   Anjali  South   Mobile  52605  33403
198      2199  2026-02-03     Neha  North   Laptop  57296  39944
199      2200  2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [4]:
df= df.drop_duplicates()

In [5]:
df

     Order_ID  Order_Date Customer Region  Product  Sales   Cost
0        2001  2026-01-21     Neha   West   Laptop  16494  13135
1        2002  2026-01-07   Anjali  North  Monitor  35140  19722
2        2003  2026-01-28    Vikas  North   Mobile  18889  13511
3        2004  2026-01-04    Kiran  North   Mobile  89657  66187
4        2005  2026-03-02    Rahul   West   Laptop  35977  20290
..        ...         ...      ...    ...      ...    ...    ...
195      2196  2026-01-26    Kiran   East  Printer  28305  16671
196      2197  2026-01-04   Suresh  South  Printer  18669  13476
197      2198  2026-03-01   Anjali  South   Mobile  52605  33403
198      2199  2026-02-03     Neha  North   Laptop  57296  39944
199      2200  2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [6]:
# FIX DATE COLUMN

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [7]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        2001 2026-01-21     Neha   West   Laptop  16494  13135
1        2002 2026-01-07   Anjali  North  Monitor  35140  19722
2        2003 2026-01-28    Vikas  North   Mobile  18889  13511
3        2004 2026-01-04    Kiran  North   Mobile  89657  66187
4        2005 2026-03-02    Rahul   West   Laptop  35977  20290
..        ...        ...      ...    ...      ...    ...    ...
195      2196 2026-01-26    Kiran   East  Printer  28305  16671
196      2197 2026-01-04   Suresh  South  Printer  18669  13476
197      2198 2026-03-01   Anjali  South   Mobile  52605  33403
198      2199 2026-02-03     Neha  North   Laptop  57296  39944
199      2200 2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [8]:
df= df.dropna(subset=['Order_Date'])

In [9]:
df['Profit'] = df['Sales']-df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

In [10]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,2001,2026-01-21,Neha,West,Laptop,16494,13135,3359,2026,1
1,2002,2026-01-07,Anjali,North,Monitor,35140,19722,15418,2026,1
2,2003,2026-01-28,Vikas,North,Mobile,18889,13511,5378,2026,1
3,2004,2026-01-04,Kiran,North,Mobile,89657,66187,23470,2026,1
4,2005,2026-03-02,Rahul,West,Laptop,35977,20290,15687,2026,3
...,...,...,...,...,...,...,...,...,...,...
195,2196,2026-01-26,Kiran,East,Printer,28305,16671,11634,2026,1
196,2197,2026-01-04,Suresh,South,Printer,18669,13476,5193,2026,1
197,2198,2026-03-01,Anjali,South,Mobile,52605,33403,19202,2026,3
198,2199,2026-02-03,Neha,North,Laptop,57296,39944,17352,2026,2
199,2200,2026-02-21,Priya,East,Mobile,12701,10702,1999,2026,2

In [23]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from getpass import getpass

password = getpass("Enter your MySQL password: ")

connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password=password,
    host="localhost",
    port=3306,
    database="sales_db"
)

engine = create_engine(connection_url)

with engine.connect() as connection:
    print("MySQL connected successfully!")

Enter your MySQL password: ········
MySQL connected successfully!

In [24]:
df.to_sql(name='sales_data',con=engine,if_exists='append',index=False)

200